/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textminingbrowser;

import java.awt.List;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import static textminingbrowser.Artikel.getFilterKata;
import static textminingbrowser.TextMiningBrowser.getBobot;
import static textminingbrowser.TextMiningBrowser.getDokFrek;
import static textminingbrowser.TextMiningBrowser.getInverseDokFrek;
import static textminingbrowser.TextMiningBrowser.getTFFromArtikel;
import static textminingbrowser.TextMiningBrowser.initDoubleNol1D;
import static textminingbrowser.TextMiningBrowser.initNol1D;
import static textminingbrowser.TextMiningBrowser.initNol2D;
import static textminingbrowser.TextMiningBrowser.printDokFrek;
import static textminingbrowser.TextMiningBrowser.printInverseDokFrek;
import static textminingbrowser.TextMiningBrowser.printTermFrek;

/**
 *
 * @author ASUS
 */
public class Searching extends javax.swing.JFrame {

    /**
     * Creates new form Searching
     */
    public Searching() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField_user = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_res_1 = new javax.swing.JPanel();
        judul_1 = new javax.swing.JLabel();
        link_1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        abstrak_1 = new javax.swing.JTextPane();
        panel_res_2 = new javax.swing.JPanel();
        judul_2 = new javax.swing.JLabel();
        link_2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        abstrak_2 = new javax.swing.JTextPane();
        panel_res_3 = new javax.swing.JPanel();
        judul_3 = new javax.swing.JLabel();
        link_3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        abstrak_3 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        textField_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_user.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        textField_user.setForeground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Discover Your Related Research Here !!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/logo3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textField_user, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21))))
        );

        jPanel2.setBackground(new java.awt.Color(254, 255, 245));

        panel_res_1.setBackground(new java.awt.Color(255, 255, 251));
        panel_res_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        panel_res_1.setMaximumSize(new java.awt.Dimension(667, 32767));

        judul_1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        judul_1.setText("Ini Judul Artikel");

        link_1.setText("http://www.researchgates.com/");

        abstrak_1.setBorder(null);
        abstrak_1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jScrollPane2.setViewportView(abstrak_1);

        javax.swing.GroupLayout panel_res_1Layout = new javax.swing.GroupLayout(panel_res_1);
        panel_res_1.setLayout(panel_res_1Layout);
        panel_res_1Layout.setHorizontalGroup(
            panel_res_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_res_1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_res_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_res_1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_res_1Layout.createSequentialGroup()
                        .addGroup(panel_res_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(link_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(judul_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        panel_res_1Layout.setVerticalGroup(
            panel_res_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_res_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_res_2.setBackground(new java.awt.Color(251, 255, 255));
        panel_res_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        panel_res_2.setMaximumSize(new java.awt.Dimension(667, 32767));

        judul_2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        judul_2.setText("Ini Judul Artikel");

        link_2.setText("http://www.researchgates.com/");

        abstrak_2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jScrollPane3.setViewportView(abstrak_2);

        javax.swing.GroupLayout panel_res_2Layout = new javax.swing.GroupLayout(panel_res_2);
        panel_res_2.setLayout(panel_res_2Layout);
        panel_res_2Layout.setHorizontalGroup(
            panel_res_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_res_2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_res_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_res_2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_res_2Layout.createSequentialGroup()
                        .addGroup(panel_res_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(link_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(judul_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        panel_res_2Layout.setVerticalGroup(
            panel_res_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_res_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_res_3.setBackground(new java.awt.Color(251, 255, 255));
        panel_res_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        panel_res_3.setMaximumSize(new java.awt.Dimension(667, 32767));

        judul_3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        judul_3.setText("Ini Judul Artikel");

        link_3.setText("http://www.researchgates.com/");

        abstrak_3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jScrollPane4.setViewportView(abstrak_3);

        javax.swing.GroupLayout panel_res_3Layout = new javax.swing.GroupLayout(panel_res_3);
        panel_res_3.setLayout(panel_res_3Layout);
        panel_res_3Layout.setHorizontalGroup(
            panel_res_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_res_3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_res_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_res_3Layout.createSequentialGroup()
                        .addComponent(judul_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(panel_res_3Layout.createSequentialGroup()
                        .addGroup(panel_res_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                            .addComponent(link_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        panel_res_3Layout.setVerticalGroup(
            panel_res_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_res_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_res_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_res_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_res_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panel_res_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_res_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_res_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jButton2.setBackground(new java.awt.Color(255, 102, 51));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NEXT");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 102));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PREV");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    static ArrayList<Artikel> listArtikel = new ArrayList<>(); //siapkan tempat untuk list of Artikel (DATABASE)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //-------------------------- 2. get inputan user
        
        String inputUser ;
        String term[];
        
        inputUser = textField_user.getText();
        term = getTerms(inputUser);
        int nArtikelBase = listArtikel.size();
        int nTerm = term.length;
        //----------------3. defining [term frequency]->tf, (word->how much term(word) in each document)
        //dok1 term1 term2
        //dok2 term1 term2
        //dok3 term1 term2
        int termFrek[][] = new int[nArtikelBase][nTerm];
        termFrek = initNol2D(termFrek);
        for(int i=0; i<nArtikelBase ; i++){
            termFrek[i] = getTFFromArtikel(term,listArtikel.get(i)); //get termcount perdokumen
        }
        printTermFrek(termFrek);
        
        //---------------- 4. defining [document frequency]-df, (term->how much document consisting those terms)
        int dokFrek[] = new int[nTerm];
        dokFrek = initNol1D(dokFrek);
        dokFrek = getDokFrek(termFrek);
        printDokFrek(dokFrek);
        
        //---------------- 5. defining [inverse document frequency]- idf, idf term = (1 + log(nArtikel/df term))
        double inverseDokfrek[] = new double[nTerm];
        inverseDokfrek = initDoubleNol1D(inverseDokfrek);
        inverseDokfrek = getInverseDokFrek(nArtikelBase,dokFrek);
        printInverseDokFrek(inverseDokfrek);
        
        //---------------- 6. defining tf*idf (pembobotan perdokumen)> kalikan term frekuensi dengan bobot kemunculan term(idf)
        //4,5 -> dok1
        //5,6 -> dok2
        double bobotDok[] = new double[nArtikelBase]; //preparing arrays of pair jarak and index of image
        bobotDok = initDoubleNol1D(bobotDok);
        bobotDok = getBobot(termFrek, inverseDokfrek);
        
        //----------------- 7 as LAST.do Sort for the array consisting val of bobot
        
        for(int i=0 ; i<bobotDok.length;i++){
            pairJarakIndex[i][0] = bobotDok[i];  //bobot
            pairJarakIndex[i][1] = i; //index of artikel
        }
        //descending
        System.out.println(" ");
        Arrays.sort(pairJarakIndex, (b, a) -> Double.compare(a[0], b[0]));
        for(int i=0;i<bobotDok.length;i++){
                System.out.println("sorted? "+pairJarakIndex[i][0]+" "+pairJarakIndex[i][1]);
        }
        
        int idx ;
        idx = (int) pairJarakIndex[0][1];
        judul_1.setText(listArtikel.get(idx).getTitle());
        //-------------------------------------done
        int k =3; //1 page tampilkan 3 source
        
            
        int page = nArtikelBase/3;
        if(nArtikelBase%3!=0)
            page+=1;
        setAllPages(page);
        System.out.println("row:"+page);
//        int pagination = row/k;
        
        for(pagination=0 ; pagination<1 ;pagination++){
            for(int j=0 ; j<k ; j++){
                int indx=0;
                indx = (int)(pairJarakIndex[(pagination*k)+j][1]);
                Artikel abstrak = new Artikel();
                abstrak = listArtikel.get(indx);
                if(j==0){
                    judul_1.setText(abstrak.getTitle());
                    link_1.setText(abstrak.getHyperlink());
                    abstrak_1.setText(abstrak.getArticle());
                }if(j==1){
                    judul_2.setText(abstrak.getTitle());
                    link_2.setText(abstrak.getHyperlink());
                    abstrak_2.setText(abstrak.getArticle());
                }if(j==2){
                    judul_3.setText(abstrak.getTitle());
                    link_3.setText(abstrak.getHyperlink());
                    abstrak_3.setText(abstrak.getArticle());
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void setAllPages(int pages){
        this.allPages = pages;
    }
    double[][] pairJarakIndex = new double[listArtikel.size()][2]; //preparing arrays of pair jarak and index of image
    private int allPages;
    private int pagination=0;
    private int inisialPage=0;
    public void goToNextPage(int next){
        this.inisialPage+=next;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(pagination<allPages)
            goToNextPage(1);
        int k=3;
        for(pagination=inisialPage ; pagination<inisialPage+1 ;pagination++){
            for(int j=0 ; j<k ; j++){
                int indx=0;
                indx = (int)(pairJarakIndex[(pagination*k)+j][1]);
                Artikel abstrak = new Artikel();
                abstrak = listArtikel.get(indx);
                if(j==0){
                    judul_1.setText(abstrak.getTitle());
                    link_1.setText(abstrak.getHyperlink());
                    abstrak_1.setText(abstrak.getArticle());
                }if(j==1){
                    judul_2.setText(abstrak.getTitle());
                    link_2.setText(abstrak.getHyperlink());
                    abstrak_2.setText(abstrak.getArticle());
                }if(j==2){
                    judul_3.setText(abstrak.getTitle());
                    link_3.setText(abstrak.getHyperlink());
                    abstrak_3.setText(abstrak.getArticle());
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void goToPrevPage(int prev){
        this.inisialPage-=prev;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(pagination>0)
            goToPrevPage(1);
        int k=3;
        for(pagination=inisialPage ; pagination<inisialPage+1 ;pagination++){
            for(int j=0 ; j<k ; j++){
                int indx=0;
                indx = (int)(pairJarakIndex[(pagination*k)+j][1]);
                Artikel abstrak = new Artikel();
                abstrak = listArtikel.get(indx);
                if(j==0){
                    judul_1.setText(abstrak.getTitle());
                    link_1.setText(abstrak.getHyperlink());
                    abstrak_1.setText(abstrak.getArticle());
                }if(j==1){
                    judul_2.setText(abstrak.getTitle());
                    link_2.setText(abstrak.getHyperlink());
                    abstrak_2.setText(abstrak.getArticle());
                }if(j==2){
                    judul_3.setText(abstrak.getTitle());
                    link_3.setText(abstrak.getHyperlink());
                    abstrak_3.setText(abstrak.getArticle());
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ArrayList<File> listFiles = new ArrayList<>(); //siapkan tempat untuk tampung semua file
        final File folder = new File("E:\\Users\\Nadian\\Documents\\NetBeansProjects\\DM textmining\\TextMiningBrowser\\src\\resources");
        
        //Baca resourcse 1 folder
        listFiles = listFilesForFolder(folder); ///mendapatkan semua file dari folder
        readListFiles(listFiles); //cek udah dapat file atau belum
        
        
        //tiap file yang ada di dalam folder dibaca, dibuatkan instance Artikel, constructornya tipedata File 
        for(File eachFile : listFiles){
            Artikel artikelBaru = new Artikel(eachFile);  // buat instance dari tiap file
            listArtikel.add(artikelBaru);                   //tambahkan ArtikelBaru ke dalam listArtikel
        }
        System.out.println(" jumlah artikel : "+listArtikel.size());
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searching().setVisible(true);
            }
        });
    }
    
    public static ArrayList<File> listFilesForFolder(final File folder) {
        ArrayList<File> mListFiles = new ArrayList<>();
        int counter=0;
            for (final File fileEntry : folder.listFiles()) {
                if (fileEntry.isDirectory()) {
                    listFilesForFolder(fileEntry);
                } else {
                    mListFiles.add(fileEntry);
                    //System.out.println(fileEntry.getName());
                    //System.out.println("mList: " +mListFiles.get(counter).getName());
                    counter++;
                }
            }
        return mListFiles;
        }
    
    private static void readListFiles(ArrayList<File> mFiles) {
        for(File mfile : mFiles){
            System.out.println("FILE : "+mfile.getName());
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane abstrak_1;
    private javax.swing.JTextPane abstrak_2;
    private javax.swing.JTextPane abstrak_3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel judul_1;
    private javax.swing.JLabel judul_2;
    private javax.swing.JLabel judul_3;
    private javax.swing.JLabel link_1;
    private javax.swing.JLabel link_2;
    private javax.swing.JLabel link_3;
    private javax.swing.JPanel panel_res_1;
    private javax.swing.JPanel panel_res_2;
    private javax.swing.JPanel panel_res_3;
    private java.awt.TextField textField_user;
    // End of variables declaration//GEN-END:variables

    private String[] getTerms(String mInputUser) {
        String filtered;
        filtered = mInputUser.replaceAll("[^A-Za-z ]", ""); //filter symbol of userInput
        System.out.println("simbol filtered: "+filtered);
        
        filtered = getFilterKata(filtered);               //filter kata bantu
        System.out.println("words filtered: "+filtered);
        
        //split inputan menjadi n term
        String termResult[] = filtered.split(" ");
        for(String str: termResult){
            //System.out.println("term " +str);
        }   
        return termResult;
    }

}
